<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NCI.OCPL.Api.Common" Version="4.0.0" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.19.12" />
  </ItemGroup>

</Project>
