version: "3.7"

services:
    elasticsearch:
        build:
            # Point to the root of the project.
            context: ../../
            # This path is relative to the context.
            dockerfile: integration-tests/docker-cts-listing-page-api/elasticsearch/Dockerfile
        # All of the ES settings can be set via the environment vars.
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms750m -Xmx750m
        ## These exposed ports are for debugging only. .NET +
        ## Docker + MacOS == bad scene. (.NET always wants to
        ## use the hosts name, and on a mac that is actually
        ## a virtual machine, and not on the same network.)
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            listingpagesapi:
                aliases:
                - elasticsearch

    api:
        build:
            ## We need the context of our build to be the root of the
            ## project, which is where our code lives.
            context: ../../
            ## This path is relative to the context. Fun, eh?
            dockerfile: integration-tests/docker-cts-listing-page-api/api/Dockerfile

        volumes:
            # Project root
            - ../..:/app
            # Integration configuration files we don't want in the source tree.
            - ../../integration-tests/docker-cts-listing-page-api/api/runtime/appsettings.inttest.json:/app/src/NCI.OCPL.Api.CTSListingPages/appsettings.inttest.json
            # Use the user's existing GitHub credentials
            - ~/.nuget/NuGet/NuGet.Config:/root/.nuget/NuGet/NuGet.Config

        ports:
            # Lets make it one more than the default aspnetcore app
            - "5000:5000"

        ## NOTE: This does NOT mean that this machine will wait
        ## for elasticsearch to be running, just that the
        ## elasticsearch container should be running first.
        depends_on:
            - elasticsearch

        networks:
            listingpagesapi:
                aliases:
                    - api


networks:
  listingpagesapi: